force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Aadhar_Verified__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aadhar Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/CIBIL_Score__c.field-meta.xml
<CustomField>
    <fullName>CIBIL_Score__c</fullName>
    <label>CIBIL Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CallHerokuEndPoint.cls
public with sharing class CallHerokuEndPoint implements Queueable, Database.AllowsCallouts {
    private Loan__c loanRecord;
    public CallHerokuEndPoint(Loan__c record){
        this.loanRecord = record;
    }
    public void execute(QueueableContext context) {          
            Http h = new Http();
            HttpRequest httpReq = new HttpRequest();
            httpReq.setMethod('POST');
            httpReq.setHeader('Content-Type','application/json');
            httpReq.setEndpoint('https://validate-ufl-requests.herokuapp.com/cibil');
            HttpResponse res = h.send(httpReq);
            if(res.getStatusCode() == 200){
                Map<String, Object> resMap= (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                Integer cibilScores = (Integer) resMap.get('res');
                system.debug('cibilScores is '+loanRecord.Id);              
                Loan__c ani = new Loan__c();
                ani.Id = loanRecord.Id;
                ani.CIBIL_Score__c = (Decimal)cibilScores;
                ani.Aadhar_Verified__c = true;
                Database.upsert(ani,false);
            }
            
    }
}