force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Aadhar_Verified__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aadhar Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loan__c/fields/CIBIL_Score__c.field-meta.xml
<CustomField>
    <fullName>CIBIL_Score__c</fullName>
    <label>CIBIL Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <label>Contact Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Default_By__c.field-meta.xml
<CustomField>
    <fullName>Default_By__c</fullName>
    <formula>IF(TODAY()&gt; Installment_Payment_Due_Date__c, TODAY()- Installment_Payment_Due_Date__c, 0)</formula>
    <label>Default By</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Installment_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Installment_Payment_Date__c</fullName>
    <label>Installment Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Installment_Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Installment_Payment_Due_Date__c</fullName>
    <label>Installment Payment Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <formula>IF( ISPICKVAL(Loan_Products__c , &apos;Loans for consumer durables (CD)&apos;) , 0.105 ,  IF( ISPICKVAL(Loan_Products__c , &apos;Personal Loans&apos;) , 0.13 ,IF( ISPICKVAL(Loan_Products__c , &apos;Two-Wheeler and Car Loans&apos;) , 0.09 , IF( ISPICKVAL(Loan_Products__c , &apos;Home Loans&apos;) , 0.0755 , 0 ))))</formula>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Products__c.field-meta.xml
<CustomField>
    <fullName>Loan_Products__c</fullName>
    <label>Loan Products</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loans for consumer durables (CD)</fullName>
            </value>
            <value>
                <fullName>Personal Loans</fullName>
            </value>
            <value>
                <fullName>Two-Wheeler and Car Loans</fullName>
            </value>
            <value>
                <fullName>Home Loans</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <label>Loan Purpose</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Request__c.field-meta.xml
<CustomField>
    <fullName>Loan_Request__c</fullName>
    <label>Loan Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/PAN_Card__c.field-meta.xml
<CustomField>
    <fullName>PAN_Card__c</fullName>
    <label>PAN Card</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GetLoanRecordsUser.cls
public with sharing class GetLoanRecordsUser {
    @AuraEnabled
    public static List<Loan__c> getLoanList(String userId) {
        String contactId =  [SELECT ContactId from User where Id=:userId].ContactId;
        return [SELECT Id,Name,Aadhar_Verified__c, Aadhar_Number__c, Account_Number__c, CIBIL_Score__c, Contact_Number__c,Default_By__c, Installment_Payment_Date__c, Installment_Payment_Due_Date__c, Interest_Rate__c, Loan_Amount__c, Loan_Products__c, Loan_Purpose__c, Loan_Request__c, PAN_Card__c FROM Loan__c where Customer__c=:contactId WITH SECURITY_ENFORCED];
    }
}